config/routes.rb
Help::Application.routes.draw do

  get "static_pages/pictures"
  get "static_pages/story"
  get "static_pages/gift"
  get "static_pages/letter"
  get "static_pages/save"
  get "static_pages/contact"

  scope "(:locale)", locale: /en|ru/  do 
    resources :static_pages
  end
  root to: 'static_pages#story'
  match "/:locale" => 'static_pages#story'

  

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    {:locale => I18n.locale}
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def pictures
  end

  def story
  end

  def gift
  end

  def letter
  end

  def save
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_donate.html.erb
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">  

  <!-- Identify your business so that you can collect the payments. -->  
  <input type="hidden" name="business" value="olesyalepeikina@gmail.com">  

  <!-- Specify a Donate button. -->  
  <input type="hidden" name="cmd" value="_donations">  

  <!-- Specify details about the contribution -->  
  <input type="hidden" name="item_name" value="Friends of Yana Lepeikina">  
  <input type="hidden" name="item_number" value="Save Yana Campaign">  
  <input type="hidden" name="currency_code" value="USD">  

  <!-- Display the payment button. -->  
  <input type="image" name="submit" border="0" src="https://www.paypal.com/en_US/i/btn/btn_donate_LG.gif"  
   alt="PayPal - Save Yana Campaign" target="_new">  
  <img alt="" border="0" width="1" height="1" src="https://www.paypal.com/en_US/i/scr/pixel.gif" >  

</form> 

app/views/layouts/_footer.html.erb
<br />
<div align="center"><h9>website donated by <a href="mailto:cedie@hotmail.com" style="color:blue">Design Paradise</a> © 2012
	<br />
	<br />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t "title" %></title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body background=<%= image_path("background-165.gif") %>>
<div class="container">
	<div class="row">
		<style>
		    .span9, .span3 {background-color: rgb(51,153,255);}
		    .buffer {padding: 10px;}
		</style>
		<div class="span9">
			<div class="buffer">
		    	<%= yield %>
		    	<%= render "layouts/footer" %>
		    </div>
		</div>
		<div class="span3">
			<div class="buffer">
				<%= link_to_unless_current "English", {locale: "en"}, {style: "color:white"} %> |
				<%= link_to_unless_current "русский", {locale: "ru"}, {style: "color:white"} %><br />
				<h2> <%= t "about_title" %> </h2>

				<ul class="thumbnails">
				  <li><a href="#"><img class="thumbnail" src='<%= image_path("thumbnails/yana#{ Random.new.rand(1..8).to_s }thumb.jpg") %>'></a></li>
				</ul>
				<div class="donate"><%= render "layouts/donate" %></div>
				<%= t "about_1" %>
				<br /><br />
            	<%= t "about_2" %>
            	<br /><br />
            	<%= t "about_3" %>
        	</div>
		</div>
	</div>
		
</div>
</body>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="<%= root_path %>"><%= t "yana_lepeikina" %></a>
			<div class="nav-collapse">
				<ul class="nav">
					<li><%= link_to (t "yanas_story"), static_pages_story_path %></li>
					<li><%= link_to (t "pictures"), static_pages_pictures_path %></li>
					<li><%= link_to (t "news"), static_pages_save_path %></li>
					<li><%= link_to (t "happiness"), static_pages_gift_path %></li>
					<li><%= link_to (t "letter"), static_pages_letter_path %></li>
				</ul>
			</div>
		</div>
	</div>
</div>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.price %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/gift.html.erb
<h1><%= t ".heading" %></h1>
<br />
<div class="row">
	<div class="span9">
		<p><%= t ".intro_1" %></p>
		<p><%= t ".intro_2" %><br />
			<%= t "yana_lepeikina" %><br />
			<%= t ".address_1" %><br />
			<%= t ".address_2" %><br />
			<%= t ".address_3" %><br />
			<%= t ".in_russian" %><br />
			<%= t ".rus_address_1" %><br />
			<%= t ".rus_address_2" %><br />
			<%= t ".rus_address_3" %>
		<ul class="thumbnails">
			<li>
				<iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=thgoli08f-20&o=1&p=8&l=as4&m=amazon&f=ifr&ref=ss_til&asins=B002YL4856" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
			</li>
			<li>
				<iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=thgoli08f-20&o=1&p=8&l=as4&m=amazon&f=ifr&ref=ss_til&asins=B000N56U88" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
			</li>
			<li>
				<iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=thgoli08f-20&o=1&p=8&l=as4&m=amazon&f=ifr&ref=ss_til&asins=B005VDU4TS" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
			</li>
			<li>
				<iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=thgoli08f-20&o=1&p=8&l=as4&m=amazon&f=ifr&ref=ss_til&asins=B0042ESFMK" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
			</li>
			<li>
				<iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=thgoli08f-20&o=1&p=8&l=as4&m=amazon&f=ifr&ref=ss_til&asins=B002PU9JAA" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
			</li>
			<li>
				<iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=thgoli08f-20&o=1&p=8&l=as4&m=amazon&f=ifr&ref=ss_til&asins=B001H0B0C4" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
			</li>
			<li>
				<iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=thgoli08f-20&o=1&p=8&l=as4&m=amazon&f=ifr&ref=ss_til&asins=B003ADVR3S" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
			</li>
			<li>
				<iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=thgoli08f-20&o=1&p=8&l=as4&m=amazon&f=ifr&ref=ss_til&asins=B000N1NDFK" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
			</li>
			<li>
				<iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=thgoli08f-20&o=1&p=8&l=as4&m=amazon&f=ifr&ref=ss_til&asins=B004PBHQO8" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
			</li>
			<li>
				<iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=thgoli08f-20&o=1&p=8&l=as4&m=amazon&f=ifr&ref=ss_til&asins=B003QHU9O6" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
			</li>
			<li>
				<iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=thgoli08f-20&o=1&p=8&l=as4&m=amazon&f=ifr&ref=ss_til&asins=B002SQE8QQ" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
			</li>
		</ul>
	</div>
</div>

app/views/static_pages/letter.html.erb
<h1><%= t ".heading" %></h1>
<p><%= t ".block_1" %></p>
   <p></p>
   <a href="http://www.bluemountain.com/" target="_blank" style="color:white">Blue Mountain Greeting Cards</a><br />
   <a href="http://www.123greetings.com/" target="_blank" style="color:white">123 Greetings</a><br />
   <%= t ".find_something" %><br />
   <%= t ".send_to" %><a href="mailto:olesyalepeikina@gmail.com" style="color:white">olesyalepeikina@gmail.com</a>
   <%= t ".thank_you" %>

app/views/static_pages/pictures.html.erb
<h1><%= t ".heading" %></h1>
<br />
<div class="row">
	<div class="span9">
		<ul class="thumbnails">
			<li><a href="<%= image_path("yana1.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana1thumb.jpg") %>"></a></li>
			<li><a href="<%= image_path("yana2.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana2thumb.jpg") %>"></a></li>
			<li><a href="<%= image_path("yana3.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana3thumb.jpg") %>"></a></li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="span9">
		<ul class="thumbnails">
			<li><a href="<%= image_path("yana4.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana4thumb.jpg") %>"></a></li>
			<li><a href="<%= image_path("yana5.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana5thumb.jpg") %>"></a></li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="span9">
		<ul class="thumbnails">
			<li><a href="<%= image_path("yana7.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana7thumb.jpg") %>"></a></li>
			<li><a href="<%= image_path("yana8.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana8thumb.jpg") %>"></a></li>
			<li><a href="<%= image_path("yana9.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana9thumb.jpg") %>"></a></li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="span9">
		<ul class="thumbnails">
			<li><a href="<%= image_path("yana10.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana10thumb.jpg") %>"></a></li>
			<li><a href="<%= image_path("yana11.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana11thumb.jpg") %>"></a></li>
			<li><a href="<%= image_path("yana12.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana12thumb.jpg") %>"></a></li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="span9">
		<ul class="thumbnails">
			<li><a href="<%= image_path("yana13.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana13thumb.jpg") %>"></a></li>
			<li><a href="<%= image_path("yana14.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana14thumb.jpg") %>"></a></li>
			<li><a href="<%= image_path("yana15.jpeg") %>" target="_blank"><img class="thumbnail" src="<%= image_path("thumbnails/yana15thumb.jpg") %>"></a></li>
		</ul>
	</div>
</div>

app/views/static_pages/save.html.erb
<h1><%= t ".heading" %></h1>
<br />
<br />
<iframe width="420" height="315" src="http://www.youtube.com/embed/z_e9uGKRhRU" frameborder="0" allowfullscreen></iframe>

app/views/static_pages/story.html.erb
<h1> <%= t "static_pages.title" %> </h1>
<p><%= t ".block_1" %></p><br />

<div class="row">
	<div class="span9">
		<ul class="thumbnails">
			<li><a href="<%= image_path("yana13.jpeg") %>" target="_blank" float="center"><img class="thumbnail" align="center" src="<%= image_path("thumbnails/yana13thumb.jpg") %>"></a>
			</li>
		</ul>
	</div>
</div>

<p><%= t ".block_2" %></p><br />

<div class="row">
	<div class="span9">
		<ul class="thumbnails">
			<li><a href="<%= image_path("yana5.jpeg") %>" target="_blank"><img class="thumbnail" align="center" src="<%= image_path("thumbnails/yana5thumb.jpg") %>"></a>
			</li>
		</ul>
	</div>
</div>

<p><%= t ".block_3" %></p>
<p><%= t ".block_4" %></p><br />

<div class="row">
	<div class="span9">
		<ul class="thumbnails">
			<li><a href="<%= image_path("yana3.jpeg") %>" target="_blank"><img class="thumbnail" align="center" src="<%= image_path("thumbnails/yana3thumb.jpg") %>"></a>
			</li>
		</ul>
	</div>
</div>

<p><%= t ".block_5" %></p>
<br />
<h2><%= t ".plea_heading" %></h2>
<p><%= t ".o_writing" %><br /><br />
<%= t ".o_block" %></p>
<p><img src="<%= image_path("yandex.jpg") %>" /></p>
<p><img src="<%= image_path("requisite.jpeg") %>" /></p>
<p><img src="<%= image_path("card_number.jpeg") %>" /></p>